### ISSUE TITLE
usr.bin.megasync

### ISSUE THREAD

**Issue by jalla2000** [morfikov/files#1]
Are you using this megasync apparmor profile? I tried it but I'm getting this error message:
apparmor.common.AppArmorException: 'Invalid mode rCUx in file: /etc/apparmor.d/usr.bin.megasync

Why is this? Are you using a different version of apparmor than me? I fixed the above error, but megasync still doesn't have the necessary permissions. Maybe you're using a different distro than me?

**Comment by morfikov** [comment]
Yes, I'm using it all the time, and I have no problems with the profile on my debian sid. Maybe the problem is the version of apparmor. I'm using 2.10-3+b1.
